service:
  name: api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
  environment:
    stagesTableName: ${self:custom.stagesTableName}
    ddbRegion: 'localhost'
    ddbEndpoint: 'http://localhost:8000'

custom:
  stage: ${opt:stage, self:provider.stage}
  stagesTableName: ${self:custom.stage}-stages

functions:
  ottopilot-api-savestage:
    handler: src/handlers/stage-post-handler.SaveStageHandler
    events:
      - http:
          method: post
          path: stages
  ottopilot-api-getstages:
    handler: src/handlers/stage-get-handler.GetStagesHandler
    events:
      - http:
          method: get
          path: stages

resources:
  Resources:
    StagesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.stagesTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1