service:
  name: api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
  environment:
    flowMetadataTableName: ${self:custom.flowMetadataTableName}
    flowStagesTableName: ${self:custom.flowStagesTableName}
    ddbRegion: 'localhost'
    ddbEndpoint: 'http://localhost:8000'

custom:
  stage: ${opt:stage, self:provider.stage}
  flowMetadataTableName: flow-metadata
  flowStagesTableName: flow-stages

functions:
  # Flows
  ottopilot-api-getflow:
    handler: src/handlers/flows/flows-get-handler.GetFlowsHandler
    events:
      - http:
          method: get
          path: flows/{id}
  ottopilot-api-getallflows:
    handler: src/handlers/flows/flows-get-handler.GetFlowsHandler
    events:
      - http:
          method: get
          path: flows
  ottopilot-api-createflow:
    handler: src/handlers/flows/flows-post-handler.SaveFlowHandler
    events:
      - http:
          method: post
          path: flows
  ottopilot-api-updateflow:
    handler: src/handlers/flows/flows-post-handler.SaveFlowHandler
    events:
      - http:
          method: post
          path: flows/{id}
resources:
  Resources:
    StagesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.stagesTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1